[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 3
combine_as_imports = true
use_parentheses = true
line_length = 88
lines_between_sections = 1
sections = ["FUTURE","STDLIB","THIRDPARTY","FIRSTPARTY","LOCALFOLDER"]
default_section = "THIRDPARTY"
ensure_newline_before_comments = true

[tool.black]
skip-string-normalization = true
exclude = '''
/(
    .git
    | .ipynb
)/
'''
